config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root to: 'welcome#index'
    get 'thread/index'
    get 'thread/new'
    post 'thread/new'
    post 'thread/show'
    match 'thread/show?id=:id' => 'photos#show', :via => [:get, :post]
    get 'thread/show'
    get 'thread/create'
    post 'thread/create'
    get 'thread/view'
    post 'thread/write'
    get 'thread/write'
    get 'thread/seed'
    get "welcome/index"
    get "welcome", to: "welcome#index", as: :welcome 
    resources :activities 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reply_m.rb
class ReplyM < ApplicationRecord
	#belongs_to :threadm
	belongs_to :thread_m
	validates :username, length: { in: 1..16 }
	validates :body, length: { in: 1..200 }
	include PublicActivity::Model  
  		tracked owner: ->(controller, model) { controller && controller.current_user}
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/thread_m.rb
class ThreadM < ApplicationRecord
    include PublicActivity::Model  
  		tracked owner: ->(controller, model) { controller && controller.current_user}
	has_many :reply_ms
	validates :title, length: { minimum: 2  }
	validates :username, length: { in: 1..16 }
	validates :body, length: { in: 1..200 }
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	def index  
   		@activities = PublicActivity::Activity.order("created_at desc")  
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include PublicActivity::StoreController
    
    protect_from_forgery
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    #helper_method :current_user
    #hide_action :current_user
end

app/controllers/thread_controller.rb
class ThreadController < ApplicationController
	include AlertHelper

	def param_reply
		params.require(:reply_m).permit(:username, :body)
	end

	def param_thread
		params.require(:thread_m).permit(:title, :username, :body)
	end

	def index
		@threads = ThreadM.all
	end

	def seed
		thread = ThreadM.new do |t|
					t.title = "David"
					t.username = "Code Artist"
					t.body = "Hay Hay Hay"
				end
		if thread.save
	    	redirect_to '/'
	    end
	end

	def new
		if request.post?
			@thread = ThreadM.create(param_thread)

			if @thread.valid?
				id_thread = @thread.id
				flash[:success] = "Works! New Thread has created."
    			#string interpolation = "Hello, #{name}!"
    			redirect_to "/thread/show?id=#{id_thread}"
			else
				#--OPTION 1--
				render "thread/new"
				#--OPTION 2--
				#flash[:error] = "Something Wrong! Failed to create new thread."
				#redirect_to "/thread/new"
			end
		else
			@thread = ThreadM.new	
		end
	end

	def create
		#https://www.ruby-forum.com/topic/2378990
		#@trd = ThreadM.new
		if request.post?
			#@product = Product.new({:serial => params[:serial], :value => params[:value]})
			#new_thread = params.require(:thread).permit(:title, :username, :body)
			thread = ThreadM.new do |t|
						t.title = params[:title]
						t.username = params[:username]
						t.body = params[:body]
					end
	    	#thread = ThreadM.create(new_thread)
	    	if thread.save
		    	redirect_to '/'
		    end
		end
	end

	def view
		id_thread = params[:id]
		@cur_thread = ThreadM.find_by(id: id_thread)
		@thread_reply = ReplyM.where(:thread_m_id => id_thread)
	end

	def show
		id_thread = params[:id]
		@cur_thread = ThreadM.find_by(id: id_thread)
		@thread_reply = ReplyM.where(:thread_m_id => id_thread)
		
		if request.post?
			thread = ThreadM.find_by(id: id_thread)
			if thread.valid?
				temp_com = param_reply
				temp_com[:thread_m_id] = thread.id
				@reply = thread.reply_ms.create(temp_com)
				if @reply.valid?
					id_thread = thread.id
					flash[:success] = "Works! New Comment has added."
    				redirect_to "/thread/show?id=#{id_thread}"
				else
					render "thread/show"
				end
			end
		else
			if id_thread
				@reply = ReplyM.new
			else 
				redirect_to "/"
			end
		end
	end

	def write
		if request.post?
			id_thread = params[:thread_id]
			thread = ThreadM.find_by(id: id_thread)

			if thread.valid?
				#p thread.id
				reply = thread.reply_ms.create(
							username: params[:username], 
							body: params[:body], 
							thread_m_id: thread.id
						)

		    	if reply.valid?
		    		p "Created #{ReplyM.count} reply(s)" 
		    		if reply.save
				    	redirect_to '/thread/view?id=' + thread.id.to_s 
				    end
		    	else
		    		p reply.errors
		    	end
			end
		else
			redirect_to '/'
		end
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
    def index
        @title 		= "Welcome#Index"
        @content 	= render_to_string "welcome/index"
        all_thread  = ThreadM.all
        #render_to_string(:partial => 'partial_file.html', :locals => {:variable => variable}, :format => :html)
        #@m = render_to_string :template => "template", :locals => {:sender => sender}
        thread      = render_to_string :template => "thread/index", :locals => {:@threads => all_thread}
        #render_to_string "thread/index"
        @content    = @content + thread
        render "shared/full"
    end

    def test

    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/alert_helper.rb
module AlertHelper
	def showError(passVar)
		res = ""
		if passVar.errors.full_messages.any?
			list_err = ""
			passVar.errors.full_messages.each do |error_message|
				list_err = list_err + "<li>" + error_message + "</li>"
			end

			res =   "<div class='alert alert-error'>" +
						"<ul>" +
							list_err +
						"</ul>" +
					"</div>"
		end

		res.html_safe
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)  
		case type  
			when :alert  
				"alert-danger"  
			when :notice  
				"alert-success"  
			else  
				"" 
		end  
	end
end

app/helpers/thread_helper.rb
module ThreadHelper
end

app/views/activities/index.html.erb
<h1>Listing Activities</h1>  
<table class="table table-striped table-bordered table-condensed sortable">  
    <thead>  
        <tr>  
            <th><%= "Activities"%></th>  
        </tr>  
    </thead>  
   <tbody>  
        <% @activities.each do |activity| %>  
        <tr>  
            <td valign="top">   
                <%= activity.inspect %>
                <%= activity.owner.email %>  
                <%= render_activity activity %>  
            </td>  
        </tr>  
     <% end %>  
   </tbody>  
   <tfoot>  
     <tr>  
       <td colspan="3"></td>  
     </tr>  
   </tfoot>  
 </table>  

app/views/layouts/application.html.erb
<!DOCTYPE html>   
<html>
   <head>
      <title>RoR Hello</title>
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
      <%= csrf_meta_tags %>   
   </head>
   <body>
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="brand" href="#">RoR Hello</a>
            <ul class="nav navbar-nav">    
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %> 
              <li><%= link_to "All Activities", activities_path %></li>   
              <li><%= link_to current_user.email, edit_user_registration_path %></li>
              <li><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>
              <% else %>   
              <li><%= link_to "Sign In", user_session_path %></li>
              <li><%= link_to "Register", new_user_registration_path %></li>
              <% end %>   
            </ul>
          </div>
        </div>
      </div>

      <div class="container">
         <%= render partial: "shared/flashalert" %>   
         <%= yield %>   
      </div>
   </body>
</html>

app/views/layouts/ori-application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/public_activity/thread_m/_create.html.erb
<% p activity.trackable %>
added thread  
 <% if activity.trackable %>  
  <%= link_to activity.trackable.title, thread_show_path(activity.trackable.id) %>  
 <% else %>  
  which has since been removed  
 <% end %> 

app/views/shared/_flashalert.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %> alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>   
		<p><%= value %></p>
	</div>
<% end %>

app/views/shared/_topbar.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">RoR Hello</a>
			<ul class="nav navbar-nav">    
            </ul>
            <ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>   
				<li><%= link_to "All Activities", activities_path %></li> 
				<li><%= link_to current_user.email, edit_user_registration_path %></li>
				<li><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>
				<% else %>   
				<li><%= link_to "Sign In", user_session_path %></li>
				<li><%= link_to "Register", new_user_registration_path %></li>
				<% end %>   
            </ul>
		</div>

	</div>
</div>

app/views/shared/full.html.erb
<html>
	<head>
		<base href='<%= request.base_url %>'>
		<title><%= @title %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    	<%= csrf_meta_tags %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<style>
			body {
				padding-top: 60px;
			}
		</style>
	</head>
	<body>
		<%= render partial: "shared/topbar" %>
		<div class='container'>
			<%= @content %>
		</div>
	</body>
</html>

app/views/thread/create.html.erb
<style>
	body {
		padding-top: 60px;
	}
</style>
<%= render partial: "shared/topbar" %>
<div class='container'>
	<h1>Thread#create</h1>
	<p>Find me in app/views/thread/create.html.erb</p>
	<form class="well" method="post" action="/thread/create">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	    <label>Title</label>
	    <input type="text" class="span2" name="title" value="">
	    <label>Your name</label>
	    <input type="text" class="span2" name="username" value="">
	    <label>Comment</label>
	    <textarea name="body"></textarea>
	    <br>
	    <button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>

app/views/thread/index.html.erb
<ul>
<% @threads.each do |thr| %>
	<li><a href='/thread/view?id=<%= thr.id %>'>[view] <%= thr.title %></a> | <a href='/thread/show?id=<%= thr.id %>'>[show] <%= thr.title %></a> - <%= thr.reply_ms.length %> reply(s)</li>
<% end %>
</ul>
<a class="btn btn-large btn-primary" href="/thread/create">Create</a>
<!--
	--https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to
	link_to "Profile", controller: "profiles", action: "show", id: @profile
	<a href="/profiles/show/1">Profile</a>
-->
<%= link_to "New", {controller: "thread", action: "new"}, class: "btn btn-large btn-primary" %>

app/views/thread/new.html.erb
<style>
	body {
		padding-top: 60px;
	}
</style>
<%= render partial: "shared/topbar" %>
<div class='container'>
	<h3>Thread#New</h3>
	<%= render partial: "shared/flashalert" %>
	<!--
		source:
		https://stackoverflow.com/questions/7878662/how-to-display-ruby-on-rails-form-validation-error-messages-one-at-a-time?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
	-->
	<%= showError(@thread) %>
	<%= form_for @thread, url: {action: "new"}, html: {class: "well"} do |f| %>
		<%= label_tag 'title' %>
		<%= f.text_field :title %>
		<%= label_tag 'username' %>
		<%= f.text_field :username %>
		<%= label_tag 'body', 'Comment' %>
		<%= f.text_area :body, size: "160x12" %>
		<%= tag "br" %>
		<%= f.submit "Create", class: "btn btn-success" %>
	<% end %>
	<%= debug(params) if Rails.env.development? %>
	<!--
		--http://guides.rubyonrails.org/form_helpers.html
		<form class="well" method="post" action="/thread/create">
			<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		    <label>Title</label>
		    <input type="text" class="span2" name="title" value="">
		    <label>Your name</label>
		    <input type="text" class="span2" name="username" value="">
		    <label>Comment</label>
		    <textarea name="body"></textarea>
		    <br>
		    <button type="submit" class="btn btn-primary">Submit</button>
		</form>
	-->
</div>

app/views/thread/show.html.erb
<style>
	body {
		padding-top: 60px;
	}
</style>
<%= render partial: "shared/topbar" %>
<div class='container'>
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<h3>Thread#Show: <%= @cur_thread.title %></h3>
	(ID = <%= @cur_thread.id %>) | by: <strong><%= @cur_thread.username %></strong> | Created at <i><%= @cur_thread.created_at %></i>
	<% 
		ctr = 0
		@thread_reply.each do |r| 
			ctr = ctr.next
	%>
		<hr>
		<div class="comment">
			<div class="meta">
				<%= ctr %> : <%= r.username %> <%= r.created_at %>
			</div>
			<div>
				<%= r.body %>
			</div>
	    </div>
	<% end %>
	
	<hr>
	<%= showError(@reply) %>
	<!--form reply-->
	<%= form_for @reply, url: {action: "show"}, html: {class: "well"} do |f| %>
		<%= label_tag 'username', "Your Username" %>
		<%= f.text_field :username %>
		<%= label_tag 'body', 'Comment' %>
		<%= f.text_area :body, size: "160x12" %>
		<%= hidden_field nil, :id, :value => @cur_thread.id %>
		<%= tag "br" %>
		<%= f.submit "Create", class: "btn btn-success" %>
	<% end %>
	<%= debug(params) if Rails.env.development? %>

	<!--
		<form class="well" method="post" action="/thread/write">
			<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		    <label>Your name</label>
		    <input type="text" class="span2" name="username" value="">
		    <label>Comment</label>
		    <textarea name="body"></textarea>
		    <br />
		    <input type="hidden" name="thread_id" value="<%= @cur_thread.id %>">
		    <button type="submit" class="btn btn-primary">Submit</button>
		</form>
	-->

app/views/thread/view.html.erb
<style>
	body {
		padding-top: 60px;
	}
</style>
<%= render partial: "shared/topbar" %>
<div class='container'>
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<h3><%= @cur_thread.title %></h3>
	(ID = <%= @cur_thread.id %>) | by: <strong><%= @cur_thread.username %></strong> | Created at <i><%= @cur_thread.created_at %></i>
	<% 
		ctr = 0
		@thread_reply.each do |r| 
			ctr = ctr.next
	%>
		<hr>
		<div class="comment">
			<div class="meta">
				<%= ctr %> : <%= r.username %> <%= r.created_at %>
			</div>
			<div>
				<%= r.body %>
			</div>
	    </div>
	<% end %>
	
	<hr>
	<!--form reply-->
	<form class="well" method="post" action="/thread/write">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	    <label>Your name</label>
	    <input type="text" class="span2" name="username" value="">
	    <label>Comment</label>
	    <textarea name="body"></textarea>
	    <br />
	    <input type="hidden" name="thread_id" value="<%= @cur_thread.id %>">
	    <button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>

app/views/welcome/_test.html.erb
<p>Hello <%= ENV['DATABASE_USER'] %></p>

app/views/welcome/index.html.erb
<h1>Welcome#Index</h1>
<%= render "welcome/test" %>

app/views/welcome/test.html.erb
<h1>Welcome to TEST</h1>